config/routes.rb
Rails.application.routes.draw do

  mount ChinaCity::Engine => '/china_city'

  resources :orders, only: [:index, :create, :destroy]

  resources :addresses do
    get :be_addr_default, on: :member
  end

  resources :carts
  get 'products/index'

  root "welcome#index"

  resources :sessions 
  delete "logout" => "sessions#destroy"

  resources :products

  resources :carts 

  resources :users do
    get :user_active, on: :member
  end

  namespace :admin do
    root "sessions#new"
    #resources :bases
    #resources :users
    resources :sessions, only: [:index, :create]
    resources :products
  end
end

app/models/order.rb
class Order < ActiveRecord::Base

	validates :product_id, presence: { message: "请添加商品继续结算"}
	validates :address_id, presence: { message: "收获地址不能为空"}

	belongs_to :user
	belongs_to :product
	belongs_to :address, class_name: "AddressBackup"

	def self.carts_to_orders user_id   #遍历购物车，创建订单
		user = User.find(user_id)
		Order.transaction do
			user.carts.each do | cart |
				order = Order.new
				if order.make_orders_ok? cart, order.clone_address_ok?(user.default_addr.to_i)
					order.destroy_carts cart.id
				else
					break
				end
			end
		end
	end

	def clone_address_ok? default_addr   #克隆默认地址信息
		if address_backup = AddressBackup.create( address_attr(default_addr) )
			address_backup   #返回新克隆的地址
		else
			false
		end
	end

	def make_orders_ok? cart, address_backup     #创建订单
		self.attributes = order_attr(cart, address_backup)
		if self.save
			true
		else
			false
		end
	end

	def order_attr cart, address_backup  #设置order信息
		order_attr = {:user_id => cart.user_id,
									:product_id => cart.product_id,
									:price => cart.product.price,
									:number => cart.number,
									:counts => cart.number * cart.product.price,
									:address_id => address_backup.id }
	end

	def address_attr default_addr   #设置默认地址属性, 复制地址
		address = Address.find default_addr
		address_attr = {:user_id => address.user_id,
										:province => address.province,
										:city => address.city,
										:country => address.country,
										:description => address.description,
										:consignee => address.consignee,
										:phonenumber => address.phonenumber}
	end
	
	def destroy_carts cart_id   #删除购物车商品
		Cart.find(cart_id).destroy
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	layout 'usersetting'

	before_filter :auth_user

	def index
    @orders = Order
      .page(params[:page] || 1)
      .per_page(params[:per_page] || 10)
      .order("id desc")
      .where(user_id: current_user.id)
      .includes(:user, :address)
	end

	def create
		if current_user.carts.blank?
			flash[:notice] = "订单创建失败,请购买商品"
			redirect_to :back
		elsif current_user.default_addr.blank?
			flash[:notice] = "请设置收货地址"
			redirect_to addresses_path
		elsif Order.carts_to_orders current_user.id
			flash[:notice] = "订单创建成功"
			redirect_to orders_path
		else
			flash[:notice] = "订单创建失败"
			redirect_to :back
		end
	end

	def destroy
		@order = current_user.orders.find params[:id]
		if @order.destroy
			flash[:notice] = "删除成功"
			redirect_to orders_path
		else
			flash[:notice] = "删除失败"
			redirect_to orders_path
		end
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<h1>订单列表</h1>
		<%= link_to "我的购物车", carts_path, class: "btn btn-primary" %>
		<table class="table">
			<tr>
				<th>产品名</th>
				<th>价格</th>
				<th>数量</th>
				<th>总价</th>
				<th>收货地址</th>
				<th>编辑</th>
			</tr>
			<% @orders.each do | order | %>
			<tr>
				<td><%= Product.find(order.product_id).product_name %></td>
				<td><%= order.price %></td>
				<td><%= order.number %></td>
				<td><%= order.counts %></td>
				<td><%= order.address_id %></td>
				<td>
					<%= order.address.consignee %>
					<%= order.address.phonenumber %>
					<%= ChinaCity.get(AddressBackup.find(order.address_id).province) %>
					<%= ChinaCity.get(AddressBackup.find(order.address_id).city) %>
					<%= ChinaCity.get(AddressBackup.find(order.address_id).country) %>
					<%= order.address.description %></td>
				<td>
				<td><%= link_to "删除", order_path(order.id), method: :delete, class: "btn btn-primary" %></td>
			</tr>
			<% end -%>
		</table>
		<%= will_paginate @orders %>
	</div>
	<div class="col-sm-2"></div>
</div>