config/routes.rb
Rails.application.routes.draw do

  mount ChinaCity::Engine => '/china_city'

  resources :orders, only: [:index, :create, :destroy]

  resources :addresses do
    get :be_addr_default, on: :member
  end

  resources :carts
  get 'products/index'

  root "welcome#index"

  resources :sessions 
  delete "logout" => "sessions#destroy"

  resources :products

  resources :carts 

  resources :users do
    get :user_active, on: :member
  end

  namespace :admin do
    root "sessions#new"
    #resources :bases
    #resources :users
    resources :sessions, only: [:index, :create]
    resources :products
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  validates_uniqueness_of :product_id, scope: [:user_id]

  belongs_to :user
  belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout 'usersetting'
  before_filter :auth_user

  def index
    @carts = Cart
      .page(params[:page] || 1)
      .per_page(params[:per_page] || 10)
      .order("id desc")
      .where(user_id: current_user.id)
      .includes(:user,:product)
  end


  def show
  end

  def edit
    @cart = current_user.carts.find params[:id]
  end

  def new
    @cart = Cart.new
  end

  def update
    @cart = current_user.carts.find params[:id]
    @cart.number = params[:plus] == "plus" ? @cart.number+1 : @cart.number-1
    @cart.number = @cart.number <= 0 ? 1 : @cart.number
    if @cart.save
      flash[:notice] = "数量修改成功"
      redirect_to carts_path
    else
      flash[:notice] = "数量修改失败"
      redirect_to :back  
    end
  end

  def create
    @cart = current_user.carts.new(product_id: params[:product_id])
    if @cart.save
      flash[:notice] = "加入购物车成功"
      redirect_to products_path
    else
      flash[:notice] = "添加购物车失败,该商品已经在购物车中"
      redirect_to :back
    end

  end

  def destroy
    @cart = Cart.find params[:id]
    if @cart.destroy
      flash[:notice] = "从购物车移除成功"
      redirect_to carts_path
    else
      flash[:notice] = "从购物车移除成功失败"
      redirect_to :back
    end
  end

  private

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h1>购物车列表</h1>
    <%= link_to "所有商品", products_path, class: "btn btn-primary" %>
    <table class="table table-hover">
      <tr>
      <th>产品名</th>
      <th>价格</th>
      <th>数量</th>
      <th>总计</th>
      <th>编辑</th>
      </tr>
      <tr>
        <td><%= Product.find(@cart.product_id).product_name %></td>
        <td>$:<%= Product.find(@cart.product_id).price %></td>
        <td>
          <a href="<%= minus_number_cart_path(@cart.id) %>"><span class="glyphicon glyphicon-minus"></span></a>
        <form action="#" method="get">
          <input type="text" name="number" value="<%= @cart.number %>" style="width:25px; height:25px" />
        </form>

          <a href="<%= add_number_cart_path(@cart.id) %>"><span class="glyphicon glyphicon-plus"></span></a>
        </td>
        <td></td>
        <td><%= link_to "删除", cart_path(@cart.id), method: :delete, class: "btn btn-default" %>
        </td>
      </tr>
      <tr>
        <td>保存</td>
        <td></td>
        <td></td>
        <td><a href="#" class="btn btn-success">结算</a></td>
      </tr>
    </table>


  </div>
  <div class="col-sm-2"></div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h1>购物车列表</h1>
    <%= link_to "所有商品", products_path, class: "btn btn-primary" %>
    <table class="table table-hover">
      <tr>
      <th>产品名</th>
      <th>价格</th>
      <th>数量</th>
      <th>总计</th>
      <th>编辑</th>
      </tr>
      <% counts = 0 %>
      <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.product.product_name %></td>
        <td>$:<%= cart.product.price %></td>
        <td>
          <a href="<%= cart_path(cart.id) %>" data-method="put" ><span class="glyphicon glyphicon-minus"></span></a>
          <%= cart.number %>
          <a href="<%= cart_path(cart.id, plus: 'plus') %>" data-method="put"><span class="glyphicon glyphicon-plus"></span></a>
        </td>

        <td><%= cart.number * cart.product.price %> 元</td>
        <% counts += cart.number * cart.product.price %>
        <td><%= link_to "删除", cart_path(cart.id), method: :delete, class: "btn btn-default" %>
        <%= link_to "编辑", edit_cart_path(cart.id), class: "btn btn-default" %>
        </td>
      </tr>
      <% end %>
      <tr>
        <td></td>
        <td>共计</td>
        <td><%= counts %> 元</td>
        <td><%= link_to "结算", orders_path, method: :post ,class: "btn btn-primary" %></td>
      </tr>
    </table>

    <%= will_paginate @carts %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>