config/routes.rb
Rails.application.routes.draw do

  mount ChinaCity::Engine => '/china_city'

  resources :orders, only: [:index, :create, :destroy]

  resources :addresses do
    get :be_addr_default, on: :member
  end

  resources :carts
  get 'products/index'

  root "welcome#index"

  resources :sessions 
  delete "logout" => "sessions#destroy"

  resources :products

  resources :carts 

  resources :users do
    get :user_active, on: :member
  end

  namespace :admin do
    root "sessions#new"
    #resources :bases
    #resources :users
    resources :sessions, only: [:index, :create]
    resources :products
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :product_name, presence: { message: "产品名不能为空"}
	validates :product_name, uniqueness: { message: "产品名已存在"}
	validates :description, presence: { message: "产品描述不能为空"}
	validates :price, presence: { message: "价格不能为空"}
	validates :inventory, presence: { message: "库存不能为空"}

	has_many :carts
	has_many :orders
	belongs_to :user
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
	
  def index
    @products = Product
    	.page(params[:page] || 1)
    	.per_page(params[:per_page] || 10)
    	.order("id desc")
      .includes(:user)
  end

  def new
    @product = Product.new
  end

  def show
    @product =  Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    @product.attributes = product_attr
    if @product.save
      flash[:notice] = "商品更新成功"
      redirect_to admin_products_path
    else
      flash[:notice] = "商品更新失败"
      render action: :show
    end
  end

  def create
    @product = Product.new(product_attr)
    if @product.save
    	flash[:notice] = "产品添加成功"
    	redirect_to admin_products_path
    else
    	flash[:notice] = "产品添加失败"
    	render action: :new
    end
  end

  def destroy
  	@product = Product.find params[:id]
  	if @product.destroy
  		flash[:notice] = "删除产品成功"
  		redirect_to admin_products_path
  	else
  		flash[:notice] = "删除产品失败"
  		redirect_to :back
  	end
  end

  private

  def product_attr
  	params.require(:product).permit(:product_name, :description, :price, :inventory)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product
    	.page(params[:page] || 1)
    	.per_page(params[:per_page] || 10)
    	.order("id desc")
    	.includes(:user)
  end
  
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/index.html.erb
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<h1>产品列表</h1>
		<%= link_to "添加产品", new_admin_product_path, class: "btn btn-primary" %>
		<table class="table">
			<tr>
				<th>产品名</th>
				<th>描述</th>
				<th>价格</th>
				<th>库存</th>
				<th>编辑</th>
			</tr>
			<% @products.each do | product | %>
			<tr>
				<td><%= product.product_name %></td>
				<td><%= product.description %></td>
				<td><%= product.price %></td>
				<td><%= product.inventory %></td>
				<td><%= link_to "删除", admin_product_path(product.id), method: :delete %>
            <%= link_to "编辑", admin_product_path(product.id), method: :get %>
        </td>
			</tr>
			<% end -%>
		</table>
		<%= will_paginate @products %>
	</div>
	<div class="col-sm-2"></div>
</div>

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h1>添加商品</h1>
    <%= link_to "所有产品", admin_products_path, class: "btn btn-primary" %>
    <%= form_for @product, url: admin_products_path, method: :post do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @product.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
      <div class="form-group">
        <label class= "control-label" >产品名</label>
        <%= f.text_field :product_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class= "control-label" >描述:</label>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class= "control-label" >价格:</label>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class= "control-label" >数量:</label>
        <%= f.text_field :inventory, class: "form-control" %>
      </div>
      <%= f.submit "保存", class: "btn btn-primary"  %>
    <% end -%>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <h1>查看单个商品</h1>
    <%= link_to "所有产品", admin_products_path, class: "btn btn-primary" %>
    <%= form_for @product, url: admin_product_path(@product.id), method: :put do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @product.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
      <div class="form-group">
        <label class= "control-label" >产品名</label>
        <%= f.text_field :product_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class= "control-label" >描述:</label>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class= "control-label" >价格:</label>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class= "control-label" >数量:</label>
        <%= f.text_field :inventory, class: "form-control" %>
      </div>
      <%= f.submit "保存", class: "btn btn-primary"  %>
    <% end -%>
  </div>
  <div class="col-sm-2"></div>
</div>