config/routes.rb
Rails.application.routes.draw do

  mount ChinaCity::Engine => '/china_city'

  resources :orders, only: [:index, :create, :destroy]

  resources :addresses do
    get :be_addr_default, on: :member
  end

  resources :carts
  get 'products/index'

  root "welcome#index"

  resources :sessions 
  delete "logout" => "sessions#destroy"

  resources :products

  resources :carts 

  resources :users do
    get :user_active, on: :member
  end

  namespace :admin do
    root "sessions#new"
    #resources :bases
    #resources :users
    resources :sessions, only: [:index, :create]
    resources :products
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tank后台管理</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Tank后台管理
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= root_path %>">前台</a>
              </li>
              <% if logged_in? %>
                <li><%= link_to "#{current_user.username}, 退出", session_path(session[:user_id]), method: 'delete' %></li>
                <% else %>
              <li>
                <a href="<%= new_session_path %>">登录</a>
              </li>
              <% end -%>

            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>
    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tank</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="http://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Tank
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= admin_root_path %>">后台管理</a>
              </li>
              <% if logged_in? %>
              <li>
                <a href="/logout" data-method="delete"><%= current_user.username %>, 退出</a>
              </li>
              <li>
                <%= link_to "setting", user_path(current_user), method: 'get' %>
              </li>
              <% else %>
              <li>
                <a href="<%= new_session_path %>">登录</a>
              </li>
              <% end -%>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      <%= yield %>
    </div>
    <script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/usersetting.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tank</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="http://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'usersetting' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Tank
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>

              <% if logged_in? %>
              <li>
                <%= link_to "#{current_user.username}, 退出", session_path(current_user), method: :delete %>
              </li>
              <li>
                <%= link_to "setting", user_path(current_user), method: 'get' %>
              </li>
              <% else %>
              <li>
                <a href="<%= new_session_path %>">登录</a>
              </li>
              <% end -%>

            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>

    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul id="main-nav" class="nav nav-tabs nav-stacked" style="">
                    <li class="active">
                        <a href="#">
                            <i class="glyphicon glyphicon-th-large"></i>
                            用户信息    
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="glyphicon glyphicon-credit-card"></i>
                            密码修改    
                        </a>
                    </li>

                    <li>
                        <a href="<%= addresses_path %>">
                            <i class="glyphicon glyphicon-globe"></i>
                            收货地址
                        </a>
                    </li>

                    <li>
                        <a href="<%= carts_path %>">
                            <i class="glyphicon glyphicon-calendar"></i>
                            购物车
                        </a>
                    </li>
                    <li>
                        <a href="<%= orders_path %>">
                            <i class="glyphicon glyphicon-fire"></i>
                            我的订单
                        </a>
                    </li>

                </ul>
            </div>
            <div class="col-md-10">
              <%= yield %>
            </div>
        </div>
    </div>
    <script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>